"""initial schema with analytics tables

Revision ID: dc98966dc03b
Revises: 
Create Date: 2025-07-25 02:11:29.446248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc98966dc03b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=200), nullable=False),
    sa.Column('cache_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('data_version', sa.String(length=50), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('idx_cache_expires_at', 'analytics_cache', ['expires_at'], unique=False)
    op.create_index('idx_cache_key', 'analytics_cache', ['cache_key'], unique=False)
    op.create_index('idx_cache_type_valid', 'analytics_cache', ['cache_type', 'is_valid'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('topic_number', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coherence_score', sa.Float(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_topics_last_updated', 'topics', ['last_updated'], unique=False)
    op.create_index('idx_topics_message_count', 'topics', [sa.literal_column('message_count DESC')], unique=False)
    op.create_index('idx_topics_trend_score', 'topics', [sa.literal_column('trend_score DESC')], unique=False)
    op.create_table('engagement_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('virality_score', sa.Float(), nullable=True),
    sa.Column('influence_score', sa.Float(), nullable=True),
    sa.Column('platform_metrics', sa.JSON(), nullable=True),
    sa.Column('reach_metrics', sa.JSON(), nullable=True),
    sa.Column('interaction_quality', sa.Float(), nullable=True),
    sa.Column('audience_relevance', sa.Float(), nullable=True),
    sa.Column('platform_percentile', sa.Float(), nullable=True),
    sa.Column('candidate_percentile', sa.Float(), nullable=True),
    sa.Column('engagement_velocity', sa.Float(), nullable=True),
    sa.Column('peak_engagement_time', sa.DateTime(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('calculation_method', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_engagement_calculated_at', 'engagement_metrics', ['calculated_at'], unique=False)
    op.create_index('idx_engagement_score', 'engagement_metrics', [sa.literal_column('engagement_score DESC')], unique=False)
    op.create_index('idx_engagement_virality', 'engagement_metrics', [sa.literal_column('virality_score DESC')], unique=False)
    op.create_table('message_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('political_tone', sa.String(length=50), nullable=True),
    sa.Column('tone_confidence', sa.Float(), nullable=True),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('analysis_method', sa.String(length=50), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_sentiment_analyzed_at', 'message_sentiment', ['analyzed_at'], unique=False)
    op.create_index('idx_message_sentiment_label', 'message_sentiment', ['sentiment_label'], unique=False)
    op.create_index('idx_message_sentiment_message_id', 'message_sentiment', ['message_id'], unique=False)
    op.create_table('message_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('is_primary_topic', sa.Boolean(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_topics_message_id', 'message_topics', ['message_id'], unique=False)
    op.create_index('idx_message_topics_probability', 'message_topics', [sa.literal_column('probability DESC')], unique=False)
    op.create_index('idx_message_topics_topic_id', 'message_topics', ['topic_id'], unique=False)
    op.create_table('trending_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_severity', 'trending_alerts', ['severity'], unique=False)
    op.create_index('idx_alerts_triggered_at', 'trending_alerts', ['triggered_at'], unique=False)
    op.create_index('idx_alerts_type_status', 'trending_alerts', ['alert_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_type_status', table_name='trending_alerts')
    op.drop_index('idx_alerts_triggered_at', table_name='trending_alerts')
    op.drop_index('idx_alerts_severity', table_name='trending_alerts')
    op.drop_table('trending_alerts')
    op.drop_index('idx_message_topics_topic_id', table_name='message_topics')
    op.drop_index('idx_message_topics_probability', table_name='message_topics')
    op.drop_index('idx_message_topics_message_id', table_name='message_topics')
    op.drop_table('message_topics')
    op.drop_index('idx_message_sentiment_message_id', table_name='message_sentiment')
    op.drop_index('idx_message_sentiment_label', table_name='message_sentiment')
    op.drop_index('idx_message_sentiment_analyzed_at', table_name='message_sentiment')
    op.drop_table('message_sentiment')
    op.drop_index('idx_engagement_virality', table_name='engagement_metrics')
    op.drop_index('idx_engagement_score', table_name='engagement_metrics')
    op.drop_index('idx_engagement_calculated_at', table_name='engagement_metrics')
    op.drop_table('engagement_metrics')
    op.drop_index('idx_topics_trend_score', table_name='topics')
    op.drop_index('idx_topics_message_count', table_name='topics')
    op.drop_index('idx_topics_last_updated', table_name='topics')
    op.drop_table('topics')
    op.drop_index('idx_cache_type_valid', table_name='analytics_cache')
    op.drop_index('idx_cache_key', table_name='analytics_cache')
    op.drop_index('idx_cache_expires_at', table_name='analytics_cache')
    op.drop_table('analytics_cache')
    # ### end Alembic commands ###
